/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Allow side-effect imports of CSS files (e.g. `import "../global.css"` used by NativeWind).
declare module "*.css" {}
