package com.mdzvtt.shmap.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    VALIDATION_FAILED,
    INVALID_OTP,
    OTP_EXPIRED,
    OTP_MAX_ATTEMPTS_EXCEEDED,
    INVALID_GOOGLE_TOKEN,
    GOOGLE_AUTH_FAILED,
    USER_NOT_FOUND,
    UNAUTHORIZED,
    INVALID_REFRESH_TOKEN,
    INTERNAL_SERVER_ERROR
}

