package com.mdzvtt.shmap.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    INVALID_CURRENT_PASSWORD,
    PASSWORD_UNCHANGED,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    VALIDATION_FAILED,
    INVALID_OTP,
    OTP_EXPIRED,
    OTP_MAX_ATTEMPTS_EXCEEDED,
    INVALID_GOOGLE_TOKEN,
    GOOGLE_AUTH_FAILED,
    USER_NOT_FOUND,
    INVALID_AVATAR,
    AVATAR_UPLOAD_NOT_FOUND,
    FRIEND_REQUEST_TO_SELF,
    FRIEND_REQUEST_ALREADY_SENT,
    FRIEND_REQUEST_NOT_FOUND,
    ALREADY_FRIENDS,
    UNAUTHORIZED,
    INVALID_REFRESH_TOKEN,
    METHOD_NOT_ALLOWED,
    INTERNAL_SERVER_ERROR
}
