spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 120000
      max-lifetime: 300000
      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000
      refresh-token:
        expiration: 604800000
resend:
  api-key: ${RESEND_API_KEY}
